# Generated by Django 5.2 on 2025-04-21 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_list_user_watch_list_bid_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='auction_list',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='auction_list',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auction', to=settings.AUTH_USER_MODEL),
        ),
    ]
