# Generated by Django 5.2 on 2025-04-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auction_list_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
