# Generated by Django 5.2 on 2025-05-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_list_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images/'),
        ),
    ]
