# Generated by Django 5.2 on 2025-05-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_list_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
